### ISSUE TITLE
Jekyll 4

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/twisterrob.github.io#23]
- [ ] Prerequisite https://github.com/TWiStErRob/twisterrob.github.io/issues/34
- [x] Prerequisite https://github.com/TWiStErRob/twisterrob.github.io/issues/24
- Feature request: https://github.com/github/pages-gem/issues/651
- Infeasibility explainer: https://github.com/github/pages-gem/issues/651#issuecomment-581069671

Motivations:
 * https://github.com/github/pages-gem/issues/752

Workarounds:
 * [2019](https://github.com/github/pages-gem/issues/651#issuecomment-541524364): move to Netlify or other third party.
 * [2019](https://github.com/github/pages-gem/issues/651#issuecomment-541442887): https://github.com/BryanSchuetz/jekyll-deploy-gh-pages (hacky [push to gh-pages branch](https://github.com/github/pages-gem/issues/651#issuecomment-718772283))
 * [2020](https://github.com/github/pages-gem/issues/651#issuecomment-628050375): [Deployment from a branch](https://jekyllrb.com/docs/continuous-integration/github-actions/)
 * [2022](https://github.com/github/pages-gem/issues/651#issuecomment-1197448026): Official response, GitHub Pages [custom actions workflows](https://github.com/actions/starter-workflows/blob/main/pages/jekyll-gh-pages.yml).
 * Official 2022 solution implemented in #25

## Tasks
- [ ] https://jekyllrb.com/docs/upgrading/3-to-4/

**Comment by TWiStErRob** [comment]
* Solves https://github.com/jekyll/jekyll/issues/7576
```
     Generating...
  Kramdown warning: Footnote definition for '1' on line 3 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '2' on line 4 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '3' on line 5 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '4' on line 6 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '5' on line 7 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '1' on line 6 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '1' on line 7 is unreferenced - ignoring
  Kramdown warning: Footnote definition for '1' on line 5 is unreferenced - ignoring
                    done in 10.164 seconds.
```

**Comment by mbifulco** [comment]
hi @TWiStErRob - just popping in to say thanks. Your self-documentation and a smattering of comments on a few issues and PRs in this ecosystem just helped me fix a build issue with [openapi.tools](https://openapi.tools)

It started with the changes I made here, which apparently were incompatible with something in jekyll 3.X.x: https://github.com/apisyouwonthate/openapi.tools/pull/457

I tried and failed to fix that here: https://github.com/apisyouwonthate/openapi.tools/pull/458

Before finding your comments about jekyll 4 not being supported by the old gh-pages workflow.

I ended up switching that repo over to a github action to deploy to jekyll here: https://github.com/apisyouwonthate/openapi.tools/pull/459

And we're back in action! I thought you might benefit from seeing that. Even if not - thank you!

**Comment by TWiStErRob** [comment]
Thanks for the feedback, glad you found it somehow and managed to upgrade your Pages site to a compatible version.

**Comment by TWiStErRob** [comment]
Review Ruby Sass usage after upgrade: https://github.com/TWiStErRob/twisterrob.github.io/pull/31#discussion_r1372371154, note https://jekyllrb.com/news/2022/12/21/jekyll-sass-converter-3.0-released/

**Comment by TWiStErRob** [comment]
Review setup guide in README.md, extract to DEVELOPMENT.md
